### ISSUE TITLE
Automatic close  bug

### ISSUE THREAD

**Issue by doomfire50** [yamashi/SkyrimOnline#54]
when i started skyrim he wil automatic close it begins closing after bethesda

**Comment by doomfire50** [comment]
ps i can only run it in steam but it wil be frozen at main menu

**Comment by WopsS** [comment]
Which version do you use?

**Comment by doomfire50** [comment]
the lastet

**Comment by WopsS** [comment]
From the **cpp** branch or from the **master** branch?

**Comment by doomfire50** [comment]
from the site

**Comment by WopsS** [comment]
Can you give me a link?

**Comment by doomfire50** [comment]
http://skyrim.ophelia-core.com/downloads/2014-12-24.zip

**Comment by WopsS** [comment]
Thank you.

Can you give me this informations:

Operating System
Skyrim Version
Which release of Skyrim Online you downloaded
Video Card
Enabled Mods

and if you get some errors when you run Skyrim?

And you have SKSE installed?

SkyrimOnline will run when the game is loaded, but it will be registred as **ScriptDragon** plugin.

**Comment by doomfire50** [comment]
Can you give me this informations:

Operating System: Windows 7
Skyrim Version:  Lastet Normal edition steam
Which release of Skyrim Online you downloaded 2014-12-24.zip
Video Card now gt630 but normal gtx760
Enabled Mods
skyrim high resolution texture pack
and if you get some errors when you run Skyrim?
no
And you have SKSE installed?yes

SkyrimOnline will run when the game is loaded, but it will be registred as ScriptDragon plugin.

**Comment by doomfire50** [comment]
skse automatic close and the origanal frezed in main menu

**Comment by WopsS** [comment]
So, you say if you start Skyrim from the Steam it will be freezed in main menu, right?

**Comment by doomfire50** [comment]
yes

**Comment by WopsS** [comment]
Yes for the first question or for the second one?

**Comment by doomfire50** [comment]
both

**Comment by WopsS** [comment]
Ok, first please give me a photo of your **Skyrim folder**, a photo from **Skyrim Folder\Data** and after that please remove SkyrimOnline.dll and start the game and see if it will freeze.

I don't figure out how this could happen since the plugin is just registred as **ScriptDragon** plugin and **SKSE** plugin. I can't reproduce it...

**Comment by doomfire50** [comment]
https://drive.google.com/?tab=mo&authuser=0#folders/0B_0ZTh7Sfix4UWJDRGRHWUJSMWF3X3ZtRUNTanpMdw

**Comment by WopsS** [comment]
I don't have permission to see it.

**Comment by doomfire50** [comment]
wait wrong post
https://docs.google.com/file/d/0B_0ZTh7Sfix4NjhjazJXUy1WMHM
https://docs.google.com/file/d/0B_0ZTh7Sfix4b3JmVDFQeUVSYjQ
this one meaby

**Comment by WopsS** [comment]
Again I don't have permission to see them. Can you upload them on imgur.com?

**Comment by doomfire50** [comment]
http://imgur.com/eWFyTVe
http://imgur.com/Q6TehoS

**Comment by WopsS** [comment]
And if you remove **SkyrimOnline.dll** it will freeze?

**Comment by doomfire50** [comment]
got no skyrimonline.dll

**Comment by WopsS** [comment]
Please start Skyrim and see if it will freeze.

**Comment by doomfire50** [comment]
nope it freeze and i dont have a skyrimonline.dll only myguiengine.dll

**Comment by WopsS** [comment]
Ok, if I understand correctly it will freeze without SkyrimOnline.dll, right?

MyGUIEngine.dll won't be loaded in memory if yoy don't habe SkyrimOnline.dll.

**Comment by doomfire50** [comment]
oh but how can i get skyrimonline.dll

**Comment by WopsS** [comment]
Wait, please tell me if it will freeze after you remove SkyrimOnline.dll.

**Comment by doomfire50** [comment]
So as i say i got no SkyrimOnline.dll never had doens exist in the zip

**Comment by WopsS** [comment]
It is located in **Skyrim folder\Data\SKSE\Plugins**.

**Comment by doomfire50** [comment]
stil freezing but in skse

**Comment by WopsS** [comment]
Please tell me if you removed **SkyrimOnline.dll** ...

**Comment by doomfire50** [comment]
it also freezeing both of the version skse and steam

**Comment by WopsS** [comment]
Ok, but tell me if you removed **SkyrimOnline.dll** ... 

If you removed it then the problem isn't from our mod.
If you don't removed it yet please remove it and tell me if it still freeze.

**Comment by doomfire50** [comment]
i removed it and it freezed

**Comment by WopsS** [comment]
Thank you.

Then the problem isn't from our plugin ... Please try a fresh install of **Skyrim**.

**Comment by doomfire50** [comment]
it is new installed version of skyrim!

**Comment by WopsS** [comment]
Try that.

http://help.bethsoft.com/app/answers/detail/a_id/21382/~/i-am-unable-to-launch-skyrim-past-the-bethesda-logo,-it-just-crashes-to
