### ISSUE TITLE
doesnt work?

### ISSUE THREAD

**Issue by AAO-Toyota-Inc** [yamashi/SkyrimOnline#56]
transfered all the files from rar to game folder and skyrim just starts up playing as normally. theres no server list, no sign in option, or chat. Info from nexusmods http://www.nexusmods.com/skyrim/mods/3592/? basically useless has no instructions.

**Comment by WopsS** [comment]
Hi,

This is a out of date version of this mod. The new version is here http://skyrim.ophelia-core.com/showthread.php?tid=1441 .

**Comment by AAO-Toyota-Inc** [comment]
I had tried that forums site first, and it didnt work

**Comment by WopsS** [comment]
On the new version you don't have a server selection or a login form.

You will just see the chat.

**Comment by AAO-Toyota-Inc** [comment]
nothing shows up or does anything different. there wasnt a chat

**Comment by AAO-Toyota-Inc** [comment]
i followed this install guide http://skyrim.ophelia-core.com/showthread.php?tid=177

**Comment by WopsS** [comment]
Do you place SkyrimOnline.dll in **Data\SKSE\plugins**?

**Comment by AAO-Toyota-Inc** [comment]
no i didnt, i just extracted everything into the main game folder and left it. Theres really no specific instructions anywhere saying where to put the files. they all say just extract to root folder

**Comment by WopsS** [comment]
Put it in that folder ... The guide is a little bit out of date.

**Comment by AAO-Toyota-Inc** [comment]
yea i figured with all the files just going into the root folder and then not working, that they had to go somewhere specific. New to playing on pc just got new graphics card

**Comment by WopsS** [comment]
Tell me if it works.

**Comment by AAO-Toyota-Inc** [comment]
the chat box comes up now, and its blank, no one playing with this mod?

**Comment by WopsS** [comment]
For the moment I didn't think so. It is bored to chat ... Player sync isn't implemented yet.

**Comment by AAO-Toyota-Inc** [comment]
is it still gonna be worked on so it will?

**Comment by WopsS** [comment]
Yes, we work on it.

**Comment by AAO-Toyota-Inc** [comment]
is there a way to hide the chat?

**Comment by WopsS** [comment]
For the moment no.
