### ISSUE TITLE
Documentation for Contributors

### ISSUE THREAD

**Issue by nightrise** [yamashi/SkyrimOnline#57]
Hey all ! 

Awesome to see that this project is once again picking up :). I'm interesting in contributing, but I can't find any documentation to bring me up to speed - and it doesn't seem like the code is commented with inline documentation.

Are there any docs somewhere which describe the project file heirarchy and architecture? I'm happy to put together the docs myself, but it would require me to discuss it in detail with the current contributors. Let me know!

**Comment by WopsS** [comment]
Hi,

We don't have any documentation for the current code ...

**Comment by yamashi** [comment]
You just have to worry about code/skyrimonline and code/game.

It would indeed be great if we had a doxygen type documentation and a basic readme on compiling

**Comment by nightrise** [comment]
Yeah absolutely, something like doxygen would be awesome. Thanks for the pointers, I'll start looking into those folders.

**Comment by yamashi** [comment]
Building is pretty simple go to Build/ launch Make...bat then go to projects open the sln, compile in release (debug doesnt build since we didnt pack the MyGUI libs in debug).

**Comment by WopsS** [comment]
I will do that this weeks.

**Comment by ansballard** [comment]
Any progress with the docs? I haven't used C++ in a while so they would help quite a lot if I can find the time to contribute.

**Comment by yamashi** [comment]
C++ expertise is mandatory to contribute to this project, there is a lot of low level programming to do and understanding how a vtable is implemented in assembly is not something you read in a doc.

**Comment by Paul-Moura** [comment]
Hi Yamashi,
I've been chatting with Megaman through the messaging system on http://skyrim.ophelia-core.com and he referred me to contact you by leaving a post here. I'm a C# developer but have been studying C++. I've looked over most of the code for this mod but I have a few questions. If you have sometime, I'd love to talk about this project so that I could begin contributing..

**Comment by yamashi** [comment]
Sure shoot your questions

**Comment by Paul-Moura** [comment]
Hi Yamashi,
Thank you for responding. First, what part of the code is actually communicating with the game? I saw you have a few hooks. But I wasn't able to determine what is actually sending commands to the game and retrieving object and properties from the game. 

Paul Moura

**Comment by yamashi** [comment]
https://github.com/yamashi/SkyrimOnline/blob/cpp/Code/skyrimonline/src/Engine/Controllers/SkyrimPlayer.cpp

We actually don't talk with the game we are in the same address space so we just read and write the game's memory and call the game's function directly.

**Comment by Paul-Moura** [comment]
I see. That's where I was getting a bit lost. I'll look at the code some
more and shoot you another email when another question comes up.
Thanks for your time.

On Tue, Apr 14, 2015 at 11:21 AM, yamashi <notifications@github.com> wrote:

>
> https://github.com/yamashi/SkyrimOnline/blob/cpp/Code/skyrimonline/src/Engine/Controllers/SkyrimPlayer.cpp
>
> We actually don't talk with the game we are in the same address space so
> we just read and write the game's memory and call the game's function
> directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yamashi/SkyrimOnline/issues/57#issuecomment-92949336>.
>



-- 
*Paul Jason Moura*
SGS PfiNDE, Inc.
IT Support Technician / Software Developer
Cell: 918-407-3722
Work: 918-505-3108

Personal: paul.j.moura@gmail.com
Work: paul.moura@sgs.com

**Comment by TommyIzen** [comment]
It doesn't matter whether the person looking at the code is a master or a novice, comments and documentation should be mandatory. Experts should know this is a best practice even if your code is very clean.

**Comment by yamashi** [comment]
Oh of course comments are important except that nobody contributes except for me and I understand my code, I have wasted enough time trying to make it easy for people to contribute it didn't change a thing, and when I find 3h/month to work on it, I won't spend those 3 hours writing documentation nobody will ever read.

**Comment by TommyIzen** [comment]
That's unfortunate. I'm pretty shocked a project this ambitious and awesome doesn't have an entire community of capable C++ coders ready to pitch in. Is there anything at all a non-expert can do to contribute?  I have some high-level coding experience but none with C++, though I have always wanted to learn low-level programming and have studied a little of it in my spare time.

For anyone that is interested, this is free and may actually be pretty useful.
Beej's Guide to Network Programming Using Internet Sockets: http://beej.us/guide/bgnet/

**Comment by Spartan322** [comment]
I'm not able to help if I have no docs to follow. (I don't want to have to scour the code because a (hypothetically) MoveRight function isn't thread-safe)

**Comment by yamashi** [comment]
Except this is not UE4, it's an experimental project, do see commits in the past months ? No, simply because contributing to this project does not involve a lot of coding if any. If you want documentation on using the game's API : http://www.creationkit.com/Papyrus_Introduction

Like I said I won't write tutorials in comments, if a function is called HookDirect3D9, it means it hooks Direct3D9, don't know how hooking works ? Google it.

The little app business code there is, is at most 500 lines of code, very explanatory code that does not need any documentation.
