### ISSUE TITLE
Collaboration tools

### ISSUE THREAD

**Issue by hibbydibby** [yamashi/SkyrimOnline#59]
I've been looking at your code, and the methods look pretty clever; it looks similar to how I was considering approaching this problem.

I was wondering if we could get an irc/trello/google doc/anything set up where we could post our notes, thoughts, questions, and next steps.

For example, I'm 95% sure scriptdragon is being used to expose player data, which will eventually allow animations to be synced. However, I don't *know* this, and I would like to ask it. I have quite a few other questions along these lines - such as - it's said an animation syncing solution has been found. Is it here? I don't think I see it. Will the solution be to simply pack and transfer the entire player data from scriptdragon, then insert it on the host machine?

**Comment by hibbydibby** [comment]
I was just looking at the updates for "got an actor to run like I want to!", and it looks like the animations are being handled through skse? So, modifications to skse or scriptdragon source would also be great to know about.

And I really want to know what, if anything, is in place for debugging and testing.

**Comment by WopsS** [comment]
Yamashi didn't let me work on the player sync, but from what I remember, ScriptDragon is used to create NPCs that will be the players. SKSE is used to set position and rotation to players (which are NPCs).ScriptDragon is used to make the player unable to use some keybinds (I'm not sure if it's 100% true, this is only what I rememmber. Maybe Yamashi will respond.)

**Comment by yamashi** [comment]
SkyrimTest.cpp contains everything I was doing research wise including animations.
You don't really need to know the changes I have made to skse as all the changes necessary have already been made. 
ScriptDragon allows us to call papyrus functions from C++, skse does reverse engineering research but not all of it so we have to do our part too.

As for debugging just set the release version to produce symbols and it will create minidumps on crash which you can use to debug.

**Comment by hibbydibby** [comment]
Oh great! I appreciate the quick replies.. maybe just github will be find then. After dealing with thor I was worried that others might be incredibly slow, sorry.
Thanks, when I get back to looking at the code, this should be enough info to keep me busy for a little while.

This has been a good source for skse documentation for me:
http://www.creationkit.com/Category:SKSE

Is there anything similar for scriptdragon? Also, does scriptdragon merely expose papyrus in c++? That's good, but I was hoping that it exposed more functions than papyrus. I suppose this means I don't really need access to scriptdragon documentation, as it would be somewhat analagous to papyrus documentation.

>skse does reverse engineering research but not all of it so we have to do our part too
From your investigations, would you be able to estimate what skse has arleady done, and what reverse engineering we might have to do?

I'm also curious about if you ran into any issues threading, so that I'll know what to avoid, and what your overall plan is for storing and transmitting actor information. Although I can hold off on these questions until for a little bit.

Also, is there a proper term for "all current models in the game"? Is it actors?

**Comment by Madhojo** [comment]
Just want to say, that I appreciate everyone who is still working on getting Skyrim Online working.  I wish I could help (used to program but it's been a.long time), Maybe buy you guys lunch at a panera, chipotle or something?  Lol. Can do that online from where I am.

Date: Wed, 4 Mar 2015 14:44:45 -0800

**Comment by WopsS** [comment]
@hibbydibby ScriptDragon doesn't have a wiki page ... You need to understand it from the source code.

> and what reverse engineering we might have to do?
I can tell you that, **monsters synchronization**, **quests synchronization** and so on.

> I'm also curious about if you ran into any issues threading or with performance in general.
**SkyrimOnline** doesn't use threading.

> Also, is there a proper term for "all current models in the game"? Is it actors?
I'm not 100% sure about this, but I think yes, they are "actors".

**Comment by yamashi** [comment]
The papyrus API is exactly the same thing as ScriptDragon's API.

Actors are TESObjectREFR meaning they are just handles, the rest of TESForms are the actual data, spawning an Actor requires a TESForm as it's base object (a TESNPC here). 
The TESNPC class is the actual data of the actor (an Actor stores a pointer to it), face morphs... The serialization code for TESNPCs is already in the sources as well as spawning an Actor from the packet transmitted.

**Comment by hibbydibby** [comment]
Not sure if you can answer this - but will using scriptdragon be faster or more efficient than papyrus? Or is it simply a proxy for accessing papyrus? I've seen fixes online to expand available RAM for users with a lot of mods implemented; I'm just thinking in advance about how much stress we might be putting on papyrus, in the future.

>quests synchronization

This one actually worries me the most. Even the single player vanilla game can't handle quests very well... although, I have actually thought of approaching this issue, since it would be nice to have a 'quest-fixer' tool which would probably be developed in the process.

>SkyrimOnline doesn't use threading.

Ah, well, the server uses threading, correct? But I suppose the clients don't, which is where I was worried about there being issues - so that's good.

Where I think I will start with will be to create some debugging/testing tools and scripts. I'll probably progress like this, unless you think it doesn't make sense:
1) write a mod to create an actor in front of the player and have them run across the screen
2) set up a local server
3) write a mod to send a "message" to the server from a virtual player (or perhaps my own player)
4) write a mod that sends animation data to the server, which is then sent back to my client, to achieve the same result of step 1 of having an actor run across the screen. Probably expand this mod so that there is one "in-game" actor and one "server-delivered" actor
5) develop a series of similar mods for testing/synchronizing various actions

The first few steps will probably keep me busy for a couple of weeks, haha. I can also write up documentation as I go, if you would like. I think if we can get a basic process down, we could open up a lot of the animation and quest synchronization testing to the broader skyrim community.

Btw, where is the IP address of the server? I'm assuming it's hardcoded into a source file atm? I'd like to change it to 127.0.0.1

**Comment by yamashi** [comment]
Yes ScriptDragon is just a proxy, it converts the arguments to a papyrus stack and calls the papyrus method. We won't be putting any stress on papyrus, our usage is very limited (i.e. placing actors and grabbing the player reference). 

The server does not use threading either, as all it does is route packets to players it is actually not stressed at all.

The skyrim community has never been of any help to the project code wise, the community is very active, but not many C++ engineers out there want to spend time doing this kind of work.

I suggest you use SkyrimOnline to test, use SkyrimTest.cpp, it was created for that particular purpose, trying shit.

The IP is indeed hardcoded in World.cpp, in fact it's already hardcoded to 127.0.0.1 ^^

**Comment by hibbydibby** [comment]
Ah, I guess a lot of mods might do calculations in papyrus, which might be what bogs it down.

>The IP is indeed hardcoded in World.cpp, in fact it's already hardcoded to 127.0.0.1 ^^

How does the client know which server to connect to? How do I know if I'm connected to my localhost? It looks like things should be logged when I connect, but I'm not seeing anything appended to my log.

So m_test needs to be uncommented to invoke SkyrimTest. So m_test will be the server that I connect to. Will it simply be a loop of the Update() function? I'm not too sure what to expect. I'll know soon enough though. I'm guessing there will be a conflict if both m_world and m_test are uncommented.

**Comment by hibbydibby** [comment]
Oh - and what is the difference between Game.exe and Game_d.exe?

**Comment by WopsS** [comment]
> How does the client know which server to connect to?

For the moment he can't.

**program_d.exe** is in compiled in debug mode. 
**_d** si debug.

**Comment by yamashi** [comment]
I just hard code the public server IP when I do a release, rest of the time it's just 127.0.0.1.

The server "game.exe" should display a message when you connect.

**Comment by hibbydibby** [comment]
Great! I was using SkyrimOnline.dll from the release.. as it was easier to copy-paste, lol. So with the one I built, I'm connected to my local server.

Ah.. I want to spend all night learning how to add to this now.. but.. jobs...

**Comment by WopsS** [comment]
I recommend you to make a symbolic link to SkyrimOnline.dll in **Build** directory.

**Comment by yamashi** [comment]
Damn I never thought about doing this, ty for the tip, I have been copy/pasting for years :(

**Comment by WopsS** [comment]
You're welcome :+1:  :)

**Comment by yamashi** [comment]
Also I am trying to keep the code very clean, so we have very strict coding standards, you should be able to understand them by reading the code (except SkyrimTest.cpp) until I add it to the readme.

**Comment by hibbydibby** [comment]
>I recommend you to make a symbolic link to SkyrimOnline.dll in Build directory.

I thought windows didn't have anything like ln! This is handy, haha.

>Also I am trying to keep the code very clean

I think I can see a lot of it, and I'll try to write similar code, we can go over it when I get to submitting things.

Now, I really like to litter my code with debugging things, sometimes adding things such as:
DEBUG_FLAG = 1
if DEBUG_FLAG == 1
{
    print(results)
}

Would you recommend I set up two local repositories? One with all my debugging crap, and one without it? (I've been doing freelance web design, and my college projects never used version control, so I'm just not sure if there's an effective way to solve this)

Finally, if I were to add some console commands (for debugging/testing) would you prefer they be parsed by the message box, parsed by the Skryim in-game console, or do you not want console commands at all? (I would probably still write a few for personal use)

**Comment by WopsS** [comment]
@hibbydibby we use **Visual Studio** debugger. We attach it to Skyrim and that's all.

**Comment by hibbydibby** [comment]
What about commands such as 'reconnect' or 'disconnect' or 'connectto $SERVER'?

**Comment by TheMeGaMaN** [comment]
Btw hibby, about Thor.
It turned out that he wasn't really a good coder (HTML only) and he for who knows what reason decided to impose that he actually worked on the mod. Probably he didn't understand that this is quite big project. Anyway after finding out and he didn't care, i banned him and pretty much forgot that he exists :)

Happy that you are interested in the mod though. Having dedicated coders can never be a bad thing.
There certainly has been lots of progress in the past few weeks compared to 2013-2014.

**Comment by WopsS** [comment]
@hibbydibby we will disconect the player when he enter in **loading screen** and reconnect it again when it is finished.
