### ISSUE TITLE
Compiling error - LNK1181: cannot open input file 'MyGUI.DirectXPlatform.lib'

### ISSUE THREAD

**Issue by hibbydibby** [yamashi/SkyrimOnline#60]
I'm using Visual Studio 2013. What version of visual studio are you using? Jw, I might switch to it. 

When I try to compile I get this error:
Error	5	error LNK1181: cannot open input file 'MyGUI.DirectXPlatform.lib'	C:\projects\SkyrimOnline\Build\projects\          LINK	SkyrimOnline

I used the Configuration Manager and selected PubRel - in another thread you said the project is lacking the MyGUI source, so debug wouldn't compile. I could be mistaken on how to disable compiling a debugging binary.

I recently started trying to compile MyGUI, and it's kind of a pain (I can't figure out why it's not finding freetype), but I'll keep looking into it.

**Comment by yamashi** [comment]
Looks like your lib is readonly, try removing the readonly flag.

**Comment by hibbydibby** [comment]
When I go to Build/lib, there is no MyGUI.DirectXPlatform.lib. Perhaps the libraries are being built out of order?

**Comment by yamashi** [comment]
Your pull most likely failed as the libs are in the folder : https://github.com/yamashi/SkyrimOnline/tree/cpp/Build/lib

**Comment by hibbydibby** [comment]
Recloning fixed the issue.. I brought that one on myself. Thanks.

I'll open a new issue for the original problem I was running into. If you don't get to it today, no worries.. I need to get back to work myself.
