### ISSUE TITLE
Write a python code generator for packets

### ISSUE THREAD

**Issue by yamashi** [yamashi/SkyrimOnline#61]
The current packet generation system is not open source so I am unable to push it online, it would be great if we could have our own based on python.
I will commit the seed XML file soon.

**Comment by WopsS** [comment]
Why in python. Can I do this in **C#**?

**Comment by yamashi** [comment]
No we need something batch friendly, as in I want to be able to run the code generation without having to build anything. Python allows to do that by running python script.py

**Comment by hibbydibby** [comment]
WopsS - I've been using python for the past year. It's obnoxiously simple. I actually don't like it for how simple it is haha. Although, it can be messy in that much of the reference material online is still for python 2.7, but I like to use 3.4..

Do you use 2.7 or 3.4 yamashi?

Could you recommend something to read on packet generation? Even if I don't work on this, I would like to read about it and understand it.

**Comment by WopsS** [comment]
@hibbydibby that's not a problem. 

I have an idea about what **yamashi** want to generate, he need this:
- Packet name. (this is a class)
 - type name. (Defined number of members)
 - **Serialize** function with **WriteBuffer** as parameter.
 - **Deserialize** function **ReadBuffer** as parameter.

**Comment by yamashi** [comment]
2.7 or 3.4, I don't care, the person who will be doing this will chose the version.
As for packet gen it's just a tool to generate C++ from XML see code/messages, the files were generated from an XML file.

**Comment by WopsS** [comment]
@yamashi can you give me an example?

**Comment by yamashi** [comment]
https://github.com/yamashi/SkyrimOnline/blob/cpp/Code/messages/Protocol.xml

**Comment by WopsS** [comment]
Thank you.

**Comment by WopsS** [comment]
@yamashi do you want to create a **text** file or **cpp** file?

**Comment by yamashi** [comment]
From the XML file you need to output the files you can find in 
https://github.com/yamashi/SkyrimOnline/tree/cpp/Code/messages/Server
and 
https://github.com/yamashi/SkyrimOnline/tree/cpp/Code/messages/Client

**Comment by WopsS** [comment]
Oh, ok.

**Comment by hibbydibby** [comment]
Is that the XML file that is currently being used?

I'm pretty sure I could write most of that. However, I wouldn't know how to know which libraries to import or what the class name is, unless I hardcode it. That is, I don't see anything defining to include "PacketHandler.h" or that the class and file should be named "GameCli_Handler".

I could hardcode it, or modify the structure of the xml so it has something like <include></include>. I'm not sure how to gracefully define the class names without having like, a namespace tree in the xml.

If this is ONLY going to be used for these files, then I can hardcode it and it should be pretty straightforward. If you want a script that can be used throughout the project, then that's the issue that I would run into (from briefly looking at it).

I won't have much time to put into this until mid next week at the earliest.

**Comment by WopsS** [comment]
Hmm, the current files was generated with a library, like **cogapp**?

**Comment by yamashi** [comment]
The thing "GameCli" is the combination of the origin field, GameCli means origin="Game" destination="Cli" and CliGame means origin="Cli" destination="Game", the current tools takes two arguments, the origin and the destination then it only looks at the packets with a matching origin.

PacketHandler.h is to be hardcoded.

Never heard of cogapp, the tool I use is not opensource so I can't release it in the project.

**Comment by WopsS** [comment]
@yamashi I got it about the tool. But I want to know if your tool use an indentation tool or indent it manually.

**Comment by yamashi** [comment]
You will have to do everything manually.

**Comment by WopsS** [comment]
I like this way :+1:

**Comment by hibbydibby** [comment]
>@hibbydibby do you want to do it or I will do it?

I can call this one; it would probably be more efficient for you to work on other parts of the code which I don't understand yet. I'll post here if I start into, and if you end up doing it sooner then nbd.

**Comment by WopsS** [comment]
@hibbydibby have you made any progress?

**Comment by hibbydibby** [comment]
Hi, sorry - I got very sick 2 weeks ago. I'm a bit behind with my work, but I ought to be able to get to it by this weekend.

**Comment by TheMeGaMaN** [comment]
Wondering if anyone of you has made any significant progress or has it been busy months with little time for the mod?

**Comment by Paul-Moura** [comment]
I started a new job so I've been busy. Also my wife is pregnant which makes my time difficult plan. But I still want to work on the mod. 

Paul Moura
