### ISSUE TITLE
Compiling error - LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' in GameCli_Hander.obj

### ISSUE THREAD

**Issue by hibbydibby** [yamashi/SkyrimOnline#62]
I'm running into this series of errors:
https://gist.github.com/hibbydibby/3e2a5cc00fc843f3c809

I believe solving this one will solve most of them:
LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' does not match value '2' in GameCli_Hander.obj

What I have tried:
right-click SkyrimOnline in the Solution Explorer > Properties > C/C++ Preprocessor settings
appended _ITERATOR_DEBUG_LEVEL=0 to the list of Preprocessor Definitions.

However, this causes _ITERATOR_DEBUG_LEVEL clashes with the rest of the libraries, such as boost, Network_d, mhook, etc. for being set to '0' instead of '2'.

If I add _ITERATOR_DEBUG_LEVEL=2 to SkyrimOnline Preprocessor Definitions I get a clash with... MyGUI.DirectXPlatform.lib. It seems to me that there is a mixture of what build flags are being set on the libraries distributed with the source code.

As another question - would it be fine to manually set all the iterator debug levels to '0'? And is there an easy way to do that without editing each one individually?

**Comment by yamashi** [comment]
Don't build PriDeb, it just won't work.

**Comment by hibbydibby** [comment]
ahhh.. didn't mean to do that.. I hate how sometimes visual studio uses "Save/Accept" and sometimes 'Close' autosaves.

For posterity, Build > Configuration Manager. Select PubRel from the 'Active solution configuration' dropdown.

Thanks again.

**Comment by WopsS** [comment]
You can build it on **PriRel** too.
