### ISSUE TITLE
All about animations

### ISSUE THREAD

**Issue by hibbydibby** [yamashi/SkyrimOnline#65]
Github isn't going to be able to format this well - when the time comes I might look into setting up a wiki. Oh - a few google excel docs might also work.

Does anyone involved have working source code for exposing and setting animations on actors? I've been digging around on this for quite a while now - I'm sure a lot of mods are doing what I want to do, but it's really hard to find source code.

Some SKSE or scriptdragon source code that manipulates actors would be fantastic. Also, the names of actual animations. I've been using char * myAnim = "Dance"; since it was given as an example on a creation kit page, but I'm not sure if "Dance" is an actual animation or not.

For keeping this concise, I don't want to list what I've tried. Most functions seem to be returning 0 or -1.0000, so I'm assuming I'm not calling them correctly or they are deprecated.

Finally, is the scriptdragon source code complete? That is, is there a chance we might have to add to the functions listed in skyscript.h in order to expose more functions?

**Comment by hibbydibby** [comment]
I think what I might do next is write "if (value_changed)" operations, and log some things. I'm worried that when I try to get() animation values, I'm missing a narrow timeframe for getting the change.

**Comment by hibbydibby** [comment]
Would animations such as these come in handy? Will we be able to use these animations at all?
https://www.youtube.com/watch?v=8cKN58yshMY

**Comment by yamashi** [comment]
The update function is called for every frame, so you will not miss anything, as for animation names you can find them in the creationkit : Gameplay -> Animations -> Actors\Characters\Behaviors\0_Master.hkx

ScriptDragon can not change animations, you will have to use the IAnimationGraph interface for that.

**Comment by WopsS** [comment]
@yamashi if this ```pPacket->movement.animation ``` will be an array with all animations?

We can use **IAnimationGraph** to set the animations.

**Comment by yamashi** [comment]
No this will be handled by the internal state, we just want to send what top most state is like running, jumping...

**Comment by WopsS** [comment]
@yamashi I just found something intersting about animations.

We can get some values about animations, which is applied. With this

```cpp
m_pCharacter->actorState.flags04
m_pCharacter->actorState.flags08
```

I'm able to know this:

```cpp
m_pCharacter->actorState.flags04 & 0x200 // Players is sneaking
m_pCharacter->actorState.flags04 & 0x400 // Player is swimming
```
or with this
```cpp
m_pCharacter->actorState.flags04 & m_pCharacter->actorState.kState_Sneaking // Players is sneaking
m_pCharacter->actorState.flags04 & m_pCharacter->actorState.kState_Swimming // Player is swimming
```
